### ISSUE TITLE
Cannot connect to Supabase Postgres with mandatory SSL

### ISSUE THREAD

**Issue by thenonameguy** [igrishaev/pg2#23] opened 2024-11-09 23:29 UTC
Tested with 0.1.19 and 0.1.20.

Socket gets closed during SSL negotiation (`_preSSLStage`).
```
Trying to connect to db-spec: {:host aws-0-eu-central-1.pooler.supabase.com, :port 6543, :database postgres, :user schemamap_readonly.gwoszteemppigfoltwxo, :so-timeout 3000, :use-ssl? true}
      
Failed to establish connection to the database #error {
 :cause Socket closed
 :via
 [{:type org.pg.error.PGError
   :message cannot flush an output stream
   :at [org.pg.util.IOTool flush IOTool.java 76]}
  {:type java.net.SocketException
   :message Socket closed
   :at [sun.nio.ch.NioSocketImpl ensureOpenAndConnected NioSocketImpl.java 163]}]
 :trace
 [[sun.nio.ch.NioSocketImpl ensureOpenAndConnected NioSocketImpl.java 163]
  [sun.nio.ch.NioSocketImpl beginWrite NioSocketImpl.java 362]
  [sun.nio.ch.NioSocketImpl implWrite NioSocketImpl.java 407]
  [sun.nio.ch.NioSocketImpl write NioSocketImpl.java 440]
  [sun.nio.ch.NioSocketImpl$2 write NioSocketImpl.java 819]
  [java.net.Socket$SocketOutputStream implWrite Socket.java 1223]
  [java.net.Socket$SocketOutputStream write Socket.java 1210]
  [java.io.BufferedOutputStream flushBuffer BufferedOutputStream.java 125]
  [java.io.BufferedOutputStream implFlush BufferedOutputStream.java 252]
  [java.io.BufferedOutputStream flush BufferedOutputStream.java 240]
  [org.pg.util.IOTool flush IOTool.java 74]
  [org.pg.Connection flush Connection.java 635]
  [org.pg.Connection close Connection.java 100]
  [org.pg.Connection _preSSLStage Connection.java 349]
  [org.pg.Connection connect Connection.java 69]
  [org.pg.Connection connect Connection.java 79]
  [pg.core$connect invokeStatic core.clj 433]
  [pg.core$connect invoke core.clj 423]
```

Can be replicated with a free Supabase account, by turning on SSL required in the DB settings.

**Comment by igrishaev** [comment] 2024-11-10 05:21
Interesting, as it works fine with neon.tech and SSL. Let me reproduce it with Superbase...

**Comment by igrishaev** [comment] 2024-11-10 05:21
Interesting, as it works fine with neon.tech and SSL. Let me reproduce it with Superbase...

**Comment by igrishaev** [comment] 2024-11-10 10:56
<img width="922" alt="Screenshot 2024-11-10 at 13 56 10" src="https://github.com/user-attachments/assets/03dc5d53-fd29-494f-a22b-9b70bd5872c2">

**Comment by igrishaev** [comment] 2024-11-10 10:59
It's because in supabase, SSL is served using a custom certificate that user must download on their machine. See the "Download certificate" button above.

Next, there are two options available:
1. you import that certificate into your loca Java keystore. Then you specify the `:use-ssl?` flag, and the certificate is held by the JVM
2. You specify the SSL context manually. There is such an option in PG2 but at the moment it requires two files: the key file and the CI file. Maybe I can change it such that it requires only CA file

**Comment by igrishaev** [comment] 2024-11-10 11:00
Links:

- https://stackoverflow.com/questions/30953141/how-to-load-ssl-certificate-in-java
- https://stackoverflow.com/questions/18513792/using-sslcontext-with-just-a-ca-certificate-and-no-keystore

At the moment, you can either disable SSL in the dashboard, or try the first method when you import the certificate into Java keystore.

**Comment by thenonameguy** [comment] 2024-11-10 12:37
Thanks for investigating! Could this case be exposed by PG2 a bit more explicitly, instead of the ambigious socket error?

**Comment by igrishaev** [comment] 2024-11-10 13:51
Well, maybe I'll extend the error message with some suggestions. But on Java level, it's impossible to know the real cause. The socket just gets closed with no traces.

**Comment by igrishaev** [comment] 2024-11-10 16:43
Good news, I've managed to reach supabase from pg2 using their certificate. Now thinking about the API for this case.

**Comment by igrishaev** [comment] 2024-11-12 15:08
OK this is now available in the latest release `0.1.21`. See these two new documentation sections with examples. Could you please let me know if it worked for you? cc @thenonameguy 

- https://github.com/igrishaev/pg2/blob/master/docs/ssl.md
- https://github.com/igrishaev/pg2/blob/master/docs/services.md

**Comment by igrishaev** [comment] 2024-11-13 08:48
Closing as it has been tested locally and documented. Feel free to create a follow up if something doesn't work for you.

**Closed by igrishaev** 2024-11-13 08:48 UTC

**Comment by thenonameguy** [comment] 2024-11-17 12:13
Thanks, I just got around to updating it. Works perfectly. I really like SSL API choices 👍
